import { missions } from '../web/missions.js';
import { lessonSteps } from '../web/course.js';
import { improveLessons } from './lesson-content.js';
import { challenges } from './challenges.js';

const main = body => `public class Student {\n    public static void main(String[] args) {\n${body.split('\n').map(s => '        ' + s).join('\n')}\n    }\n}\n`;
const inputMain = body => 'import java.util.Scanner;\n\n' + main('Scanner input = new Scanner(System.in);\n' + body);
const make = (id, title, topic, intro, concept, example, prediction, task, hint, reflection, starter, solution, cases) => ({ id, title, topic, intro, concept, example, prediction, task, hint, reflection, starter, solution, cases, kind: 'console' });
const originalCoreLessons = [
  make('hello-java', 'Bring the console online', 'Printing & program structure',
    'Send a two-line startup message from the robot’s diagnostic terminal.',
    'Java starts at `main`. `println` writes text and ends the line. Quotation marks surround a `String`; a semicolon ends a statement.',
    'System.out.println("Pip online");', ['What does `println` add after the text?', ['A new line', 'A space only'], 0],
    'Print `Pip online` on the first line and `Ready to learn` on the second.', 'Use two `println` statements inside `main`, with the exact text in quotes.',
    'Explain what `main`, quotation marks, and the semicolons do. What compiler error results if a semicolon is missing?',
    main('System.out.println("Pip offline");'), main('System.out.println("Pip online");\nSystem.out.println("Ready to learn");'), [{ input: '', expected: 'Pip online\nReady to learn' }]),
  make('java-variables', 'Count the spare parts', 'Variables & assignment',
    'The workshop starts with 12 parts. Pip uses 5. Calculate how many remain.',
    'An `int` stores a whole number. Assignment replaces the current value; it does not create a mathematical equation that stays linked.',
    'int parts = 12;\nparts = parts - 5;', ['After `x = 8; x = x + 2;` what is `x`?', ['`8`', '`10`', '`2`'], 1],
    'Use the `parts` variable, subtract `5`, and print the remaining count.', 'Update `parts` before printing it. Print the variable without quotation marks.',
    'Why does `println("parts")` print something different from `println(parts)`?',
    main('int parts = 12;\n// Subtract the five used parts.\nSystem.out.println(parts);'), main('int parts = 12;\nparts = parts - 5;\nSystem.out.println(parts);'), [{ input: '', expected: '7' }]),
  make('java-expressions', 'Read the battery fraction', 'Types, arithmetic & casting',
    'Calculate the fraction of energy remaining: 3 cells charged out of 4.',
    'Dividing two `int`s uses integer division. A `double` operand makes division keep its fractional part. Multiplication and division happen before addition.',
    'double fraction = (double) charged / total;', ['What is `3 / 4` when both operands are `int`?', ['`0`', '`0.75`'], 0],
    'Keep `charged` and `total` as `int`s. Change the `fraction` expression so it prints `0.75`.', 'Cast `charged` to `double` before division. Casting the result of `3 / 4` is too late.',
    'Predict `7 / 2`, `7 / 2.0`, and `(double) (7 / 2)`. Explain the difference.',
    main('int charged = 3;\nint total = 4;\ndouble fraction = charged / total;\nSystem.out.println(fraction);'), main('int charged = 3;\nint total = 4;\ndouble fraction = (double) charged / total;\nSystem.out.println(fraction);'), [{ input: '', expected: '0.75' }]),
  make('java-strings', 'Decode the robot label', 'Strings, `char` & indexing',
    'Read the label `PIP-07` and report its length and first character.',
    '`String.length()` counts characters. `charAt(0)` reads the first character because indexes start at zero. Strings use double quotes; a `char` uses single quotes.',
    'String label = "PIP-07";\nchar first = label.charAt(0);', ['What index reads the first character?', ['0', '1'], 0],
    'Print the label’s length, then its first character on a new line.', 'Use `label.length()` and `label.charAt(0)`, not fixed answers.',
    'What would `charAt(label.length())` do? Explain which index is the last valid one.',
    main('String label = "PIP-07";\nSystem.out.println(label);'), main('String label = "PIP-07";\nSystem.out.println(label.length());\nSystem.out.println(label.charAt(0));'), [{ input: '', expected: '6\nP' }]),
  make('java-for', 'Schedule repeated scans', '`for` loops',
    'The input says how many scans to perform. Print `Scan 1`, `Scan 2`, and so on.',
    'A `for` loop has initialization, a condition, and an update. The body runs only while the condition is `true`. The provided `Scanner` reads a test value.',
    'for (int i = 1; i <= count; i++) {\n    System.out.println("Scan " + i);\n}', ['How many times does `i = 1; i <= 3; i++` run?', ['2', '3', '4'], 1],
    'Write a loop that prints one numbered line for each scan. Zero scans should produce no output.', 'Start `i` at `1` and continue through `count`, inclusive.',
    'Trace initialization, condition, body, and update for `count = 2`. Why does `count = 0` print nothing?',
    inputMain('int count = input.nextInt();\n// Print the numbered scans with a for loop.'), inputMain('int count = input.nextInt();\nfor (int i = 1; i <= count; i++) {\n    System.out.println("Scan " + i);\n}'), [{ input: '3', expected: 'Scan 1\nScan 2\nScan 3' }, { input: '1', expected: 'Scan 1' }, { input: '0', expected: '' }]),
  make('java-nested', 'Print a sensor grid', 'Nested loops',
    'Draw a grid of `#` symbols. The input supplies rows, then columns.',
    'For each outer-loop row, the inner loop starts again and prints all columns. `print` stays on the same line; `println` ends the row.',
    'for (int row = 0; row < rows; row++) {\n    // Print every column here.\n    System.out.println();\n}', ['A 2 by 3 grid needs how many symbols?', ['5', '6'], 1],
    'Use nested loops to print `rows` lines containing `columns` `#` symbols each.', 'Put `print("#")` inside the inner loop. Put `println()` after that inner loop.',
    'Why must `println()` be outside the inner loop? Trace both counters for a 2 by 2 grid.',
    inputMain('int rows = input.nextInt();\nint columns = input.nextInt();\n// Build the grid.'), inputMain('int rows = input.nextInt();\nint columns = input.nextInt();\nfor (int row = 0; row < rows; row++) {\n    for (int col = 0; col < columns; col++) {\n        System.out.print("#");\n    }\n    System.out.println();\n}'), [{ input: '2 3', expected: '###\n###' }, { input: '1 4', expected: '####' }]),
  make('java-random-math', 'Bound a sensor reading', '`Random` & `Math`',
    'Turn a raw sensor value into a magnitude, then limit it to a maximum of 100.',
    '`Math.abs` removes a sign; `Math.min` chooses the smaller number. `Random.nextInt(6)` produces values `0` through `5`, so add `1` for a six-sided die. Randomness should be bounded and tested.',
    'int die = new Random().nextInt(6) + 1;\nint capped = Math.min(100, Math.abs(raw));', ['What can `nextInt(6)` return?', ['`0` through `5`', '`1` through `6`'], 0],
    'Read `raw` and print `Math.abs(raw)`, capped at `100`. The provided values stay between -1000 and 1000.', 'Nest `Math.abs(raw)` inside `Math.min(100, ...)`.',
    'Explain the range of the `die` expression. Why is a fixed seed useful when debugging random behavior?',
    inputMain('int raw = input.nextInt();\nSystem.out.println(raw);'), inputMain('int raw = input.nextInt();\nSystem.out.println(Math.min(100, Math.abs(raw)));'), [{ input: '-27', expected: '27' }, { input: '140', expected: '100' }, { input: '0', expected: '0' }]),
  make('java-accumulator', 'Total the charging cycles', 'Cumulative sums',
    'Add the integers from 1 through the given count to total a sequence of charging increments.',
    'Create an accumulator before the loop so its value survives every iteration. Adding to it inside the loop builds the running total.',
    'int total = 0;\nfor (int i = 1; i <= count; i++) {\n    total += i;\n}', ['Where should `total = 0` go?', ['Before the loop', 'Inside every iteration'], 0],
    'Calculate and print the sum from 1 through `count` using a loop.', 'Initialize `total` to zero once, then add `i` on each iteration.',
    'What goes wrong if `total` is reset inside the loop? Where can the loop variable `i` be used?',
    inputMain('int count = input.nextInt();\nint total = 0;\n// Accumulate the increments.\nSystem.out.println(total);'), inputMain('int count = input.nextInt();\nint total = 0;\nfor (int i = 1; i <= count; i++) { total += i; }\nSystem.out.println(total);'), [{ input: '4', expected: '10' }, { input: '0', expected: '0' }, { input: '7', expected: '28' }]),
  make('java-constants', 'Set the shelf count once', 'Scope & class constants',
    'Pip scans the same number of shelves on every trip. Store that number once, where every method can read it.',
    'A class constant is declared inside the class but outside `main`, with `public static final`. `final` blocks later assignments. A variable declared inside braces exists only within them; that region is its scope, so the loop variable `i` is gone after the loop.',
    'public static final int SHELVES = 3;', ['A `for` loop declares `int i`. Can `main` print `i` after the loop ends?', ['No — `i` is out of scope', 'Yes — `i` keeps its last value'], 0],
    'Declare `public static final int SHELVES = 3;` above `main`. Use `SHELVES` as the loop bound and in the final summary line, so the program compiles and prints every shelf.', 'The starter reads `i` outside the loop, where it no longer exists. Print `SHELVES` there instead.',
    'Why does reading `i` after the loop fail to compile? What changes in the output when `SHELVES` becomes 5, and how many lines of code change?',
    'public class Student {\n    // Declare the SHELVES constant here.\n\n    public static void main(String[] args) {\n        for (int i = 1; i <= 3; i++) {\n            System.out.println("Shelf " + i);\n        }\n        System.out.println("Scanned " + i + " shelves");\n    }\n}\n',
    'public class Student {\n    public static final int SHELVES = 3;\n\n    public static void main(String[] args) {\n        for (int i = 1; i <= SHELVES; i++) {\n            System.out.println("Shelf " + i);\n        }\n        System.out.println("Scanned " + SHELVES + " shelves");\n    }\n}\n', [{ input: '', expected: 'Shelf 1\nShelf 2\nShelf 3\nScanned 3 shelves' }]),
  make('java-methods', 'Name a repeated task', 'Methods & parameters',
    'Create an `announce` method that prints `Ready:` followed by a robot name.',
    'A method names a behavior. A parameter receives a value at the call site. Two calls can run the same instructions with different values.',
    'announce("Pip");\nannounce("Bolt");', ['Can one parameter receive different values on separate calls?', ['Yes', 'No'], 0],
    'Complete `announce(String name)`. Print `Ready:` plus a space and the supplied name.', 'Inside `announce`, use `System.out.println("Ready: " + name);`.',
    'Explain the difference between the parameter `name` and the argument `"Pip"`.',
    'public class Student {\n    public static void main(String[] args) {\n        announce("Pip");\n        announce("Bolt");\n    }\n    public static void announce(String name) {\n        // Print the announcement.\n    }\n}\n',
    'public class Student {\n    public static void main(String[] args) { announce("Pip"); announce("Bolt"); }\n    public static void announce(String name) { System.out.println("Ready: " + name); }\n}\n', [{ input: '', expected: 'Ready: Pip\nReady: Bolt' }]),
  make('java-returns', 'Return the travel distance', 'Return values',
    'Write a `distance` method that multiplies speed by duration and returns the answer.',
    'Returning a value sends it back to the caller. Printing only writes to the console. A method declared `double` must return a `double`-compatible value.',
    'double traveled = distance(2.5, 4.0);', ['Does `println` replace `return` in a `double` method?', ['Yes', 'No'], 1],
    'Replace `return 0` with the product of `speed` and `seconds`.', 'Use `return speed * seconds;` inside `distance`.',
    'Why is a returned value useful if another calculation needs the distance?',
    'import java.util.Scanner;\npublic class Student {\n    public static void main(String[] args) {\n        Scanner input = new Scanner(System.in);\n        System.out.println(distance(input.nextDouble(), input.nextDouble()));\n    }\n    public static double distance(double speed, double seconds) {\n        return 0;\n    }\n}\n',
    'import java.util.Scanner;\npublic class Student {\n    public static void main(String[] args) { Scanner in = new Scanner(System.in); System.out.println(distance(in.nextDouble(), in.nextDouble())); }\n    public static double distance(double speed, double seconds) { return speed * seconds; }\n}\n', [{ input: '2.5 4', expected: '10.0' }, { input: '0 8', expected: '0.0' }, { input: '1.2 3', expected: '3.5999999999999996' }]),
  make('java-conditionals', 'Choose a battery warning', 'Conditionals & `boolean` expressions',
    'Read a battery percentage. Print `CHARGE` below 20; otherwise print `READY`.',
    'A comparison produces `true` or `false`. `if` chooses a branch. With `if`/`else`, exactly one branch runs. Equality uses `==`, while assignment uses `=`.',
    'if (battery < 20) {\n    // Low-battery action\n} else {\n    // Ready action\n}', ['At exactly 20%, which branch runs?', ['`CHARGE`', '`READY`'], 1],
    'Replace the fixed message with an `if`/`else` based on `battery`.', 'Test the boundary: 19 should charge, 20 should be ready.',
    'Give three tests that exercise both branches and the boundary. How could `&&` combine two requirements?',
    inputMain('int battery = input.nextInt();\nSystem.out.println("READY");'), inputMain('int battery = input.nextInt();\nif (battery < 20) { System.out.println("CHARGE"); } else { System.out.println("READY"); }'), [{ input: '19', expected: 'CHARGE' }, { input: '20', expected: 'READY' }, { input: '90', expected: 'READY' }]),
  make('java-while', 'Count down to launch', '`while` loops',
    'Read a nonnegative countdown, print each value down to 1, then print `GO`.',
    'A `while` loop checks its condition before each iteration. Something must change to make the condition `false`, or it will keep running.',
    'while (count > 0) {\n    System.out.println(count);\n    count--;\n}', ['What happens if `count--` is missing for a positive `count`?', ['The loop keeps running', 'It runs once'], 0],
    'Add the countdown loop before the `GO` message.', 'Print `count` and decrement it inside the loop.',
    'Compare `for` and `while` loops. Why does a zero countdown print only `GO`?',
    inputMain('int count = input.nextInt();\n// Count down.\nSystem.out.println("GO");'), inputMain('int count = input.nextInt();\nwhile (count > 0) { System.out.println(count); count--; }\nSystem.out.println("GO");'), [{ input: '3', expected: '3\n2\n1\nGO' }, { input: '0', expected: 'GO' }]),
  make('java-scanner', 'Read a mission request', '`Scanner` input',
    'Read a robot name and a whole-number load, separated by whitespace. Print the name, a colon, and twice the load.',
    '`Scanner.next` reads one text token; `nextInt` reads an integer token. `nextLine` reads the rest of a line, including an empty remainder after a number.',
    'String name = input.next();\nint load = input.nextInt();', ['Which call reads a whole-number token?', ['`nextInt()`', '`nextLine()`'], 0],
    'Read both values, then print `name + ":" + (load * 2)`.', 'Use parentheses around the arithmetic so it happens before string concatenation.',
    'What changes if the name contains spaces? Explain the `nextInt`/`nextLine` newline issue.',
    inputMain('// Read the name and load.\nSystem.out.println("Pip:0");'), inputMain('String name = input.next();\nint load = input.nextInt();\nSystem.out.println(name + ":" + (load * 2));'), [{ input: 'Pip 4', expected: 'Pip:8' }, { input: 'Bolt 7', expected: 'Bolt:14' }]),
  make('java-arrays', 'Store sensor samples', 'Arrays & traversal',
    'Read four integer samples into an array, then print their sum.',
    'An array stores several values of one type. Indexes start at `0` and end at `length - 1`. Use `values.length` to keep traversal tied to the array size.',
    'int[] samples = new int[4];\nsamples[0] = 12;', ['For an array of length 4, what is the last index?', ['3', '4'], 0],
    'Fill `samples` using `input.nextInt()`, then loop over the array to calculate `total`.', 'Use `i < samples.length`, never `i <= samples.length`.',
    'What change would let this program read six samples without rewriting each assignment?',
    inputMain('int[] samples = new int[4];\nint total = 0;\n// Fill the array and total its values.\nSystem.out.println(total);'), inputMain('int[] samples = new int[4];\nfor (int i = 0; i < samples.length; i++) { samples[i] = input.nextInt(); }\nint total = 0;\nfor (int i = 0; i < samples.length; i++) { total += samples[i]; }\nSystem.out.println(total);'), [{ input: '1 2 3 4', expected: '10' }, { input: '-2 0 5 1', expected: '4' }]),
  make('java-references', 'Share a sensor buffer', 'Reference semantics',
    'Two variables can refer to the same array. Observe which changes affect both names.',
    'Assigning an array variable copies a reference, not the elements. If `backup` and `readings` refer to the same array, changing `backup[0]` also changes `readings[0]`.',
    'int[] backup = readings;', ['Does this assignment create a separate copy of the array?', ['Yes', 'No'], 1],
    'Make `backup` refer to `readings`, set `backup[0]` to `99`, then print `readings[0]` and `readings[1]`.', 'Replace the new array assigned to `backup` with `readings`.',
    'Draw two variables pointing to the same array. How would a loop create an independent copy?',
    main('int[] readings = {10, 20};\nint[] backup = new int[2];\nbackup[0] = 99;\nSystem.out.println(readings[0]);\nSystem.out.println(readings[1]);'), main('int[] readings = {10, 20};\nint[] backup = readings;\nbackup[0] = 99;\nSystem.out.println(readings[0]);\nSystem.out.println(readings[1]);'), [{ input: '', expected: '99\n20' }]),
  make('java-2d-arrays', 'Map the charging stations', '2D arrays',
    'A 2D array maps station availability: `1` means available, `0` means occupied. Count the available stations.',
    'A 2D array is an array of row arrays. Use `map.length` for rows and `map[row].length` for columns in that row.',
    'for (int row = 0; row < map.length; row++) {\n    for (int col = 0; col < map[row].length; col++) {\n        // Inspect map[row][col].\n    }\n}', ['Which expression reads row 1, column 2?', ['`map[1][2]`', '`map[2][1]`'], 0],
    'Use nested loops and a condition to count all the `1` values.', 'Increment `available` only when `map[row][col] == 1`.',
    'Why use `map[row].length` rather than assuming every row has the same size?',
    main('int[][] map = {{1, 0, 1}, {0, 1, 1}};\nint available = 0;\n// Count available stations.\nSystem.out.println(available);'), main('int[][] map = {{1, 0, 1}, {0, 1, 1}};\nint available = 0;\nfor (int row = 0; row < map.length; row++) {\n    for (int col = 0; col < map[row].length; col++) {\n        if (map[row][col] == 1) { available++; }\n    }\n}\nSystem.out.println(available);'), [{ input: '', expected: '4' }]),
  make('java-array-patterns', 'Find the strongest signal', 'Array algorithms & testing',
    'Read four integer signals. Find the maximum, even when all values are negative.',
    'Initialize a maximum to the first element, then compare the remaining elements. Initializing to zero fails when every element is negative.',
    'int maximum = values[0];', ['For `{-8, -3, -6}`, what is the maximum?', ['`0`', '`-3`'], 1],
    'Fill the array and use a loop to find and print its maximum.', 'Start the comparison loop at index 1 after setting `maximum = values[0]`.',
    'Design tests for all-negative values, duplicate maxima, and a maximum at the last index.',
    inputMain('int[] values = new int[4];\nfor (int i = 0; i < values.length; i++) { values[i] = input.nextInt(); }\nint maximum = 0;\n// Find the actual maximum.\nSystem.out.println(maximum);'), inputMain('int[] values = new int[4];\nfor (int i = 0; i < values.length; i++) { values[i] = input.nextInt(); }\nint maximum = values[0];\nfor (int i = 1; i < values.length; i++) { if (values[i] > maximum) { maximum = values[i]; } }\nSystem.out.println(maximum);'), [{ input: '-8 -3 -6 -9', expected: '-3' }, { input: '2 9 1 9', expected: '9' }, { input: '1 2 3 7', expected: '7' }]),
  make('java-final-report', 'Write the mission report', 'CSE 121 capstone',
    'Read a sample count, then that many battery readings. Print how many are below 20. Combine input, arrays, loops, methods, and conditions.',
    'Plan the algorithm before coding: read → store → inspect → count → report. Decompose the counting behavior into a method that takes an array and returns an `int`.',
    'int low = countLow(readings);', ['Should a reading of exactly 20 count as below 20?', ['Yes', 'No'], 1],
    'Complete `countLow`. Add a comment describing its behavior. Test an empty array, boundary values, and several low readings.', 'Loop from `0` to `readings.length - 1`. Increase a count for `readings[i] < 20`, then return the count.',
    'Describe the algorithm and tests. Who could be affected if a real robot misread a battery sensor? What checks or human oversight would help?',
    'import java.util.Scanner;\npublic class Student {\n    public static void main(String[] args) {\n        Scanner input = new Scanner(System.in);\n        int[] readings = new int[input.nextInt()];\n        for (int i = 0; i < readings.length; i++) {\n            readings[i] = input.nextInt();\n        }\n        System.out.println(countLow(readings));\n    }\n    public static int countLow(int[] readings) {\n        return 0;\n    }\n}\n',
    'import java.util.Scanner;\npublic class Student {\n    public static void main(String[] args) { Scanner input = new Scanner(System.in); int[] readings = new int[input.nextInt()]; for(int i=0;i<readings.length;i++){readings[i]=input.nextInt();} System.out.println(countLow(readings)); }\n    // Returns the number of readings strictly below 20.\n    public static int countLow(int[] readings) { int count=0; for(int i=0;i<readings.length;i++){if(readings[i]<20){count++;}} return count; }\n}\n', [{ input: '5 19 20 0 80 7', expected: '3' }, { input: '0', expected: '0' }, { input: '3 20 21 100', expected: '0' }]),
];

export const coreLessons = improveLessons(originalCoreLessons);
const robotLessons = missions.map((m, mission) => ({ ...m, title: m.short, topic: m.unit, kind: 'robot', mission, steps: lessonSteps[m.id], reflection: m.explain, assessmentVersion:mission===5?3:2, requirements:mission===5?{methods:[{name:'dock',returns:'void',parameters:['Robot','double']}]}:undefined, visual:{kind:mission<3?'drive':'branch'} }));
export const lessons = [...coreLessons, ...robotLessons,...challenges];
export const modules = [
  { id: 'basics', title: 'Start with Java', description: 'Build declarations, watch values change, and repair small mistakes.', ids: ['hello-java','java-declare','debug-semicolon','java-types','debug-types','java-variables','java-expressions','java-strings','first-movement'] },
  { id: 'loops', title: 'Make work repeat', description: 'Counted repetition, nested loops, cumulative algorithms, scope, and class constants.', ids: ['java-for','debug-loop-boundary','java-nested','java-random-math','java-accumulator','debug-reset-total','java-constants'] },
  { id: 'methods', title: 'Build reusable actions', description: 'Parameters, return values, and decomposition.', ids: ['java-methods','java-returns','precision-parking'] },
  { id: 'decisions', title: 'Respond to the world', description: 'Conditions, `while` loops, input, and robot feedback.', ids: ['java-conditionals','java-while','java-scanner','make-a-turn','sense-and-stop','collect-a-part'] },
  { id: 'arrays', title: 'Work with collections of data', description: 'Arrays, shared references, grids, and traversal patterns.', ids: ['java-arrays','debug-array-bounds','java-references','java-2d-arrays','java-array-patterns'] },
  { id: 'finish', title: 'Put it all together', description: 'Independent coding, obstacle routes, cargo, and scoring.', ids: ['autonomous-docking','java-final-report','robot-detour','robot-cargo','robot-hoop'] },
];
export const orderedLessons = modules.flatMap(m => m.ids.map(id => lessons.find(l => l.id === id)));
export function stepsFor(lesson) {
  if (lesson.steps) return lesson.steps;
  return [
    { label: 'Goal', title: lesson.title, text: lesson.intro },
    { label: 'One idea', title: lesson.topic, text: lesson.concept, code: lesson.example },
    { label: 'Predict', title: lesson.prediction[0], text: 'Choose an answer before writing the code.', choices: lesson.prediction[1], answer: lesson.prediction[2], response: lesson.concept },
    { label: 'Task', title: 'Write and test it.', task: true },
    { label: 'Explain', title: 'Apply the idea.', reflect: true },
  ];
}
