const wrap = body => `public class Student {\n    // Called at the decision rate selected above the robot.\n    public static void update(Robot robot) {\n${body.split('\n').map(line => '        ' + line).join('\n')}\n    }\n}\n`;
export const missions = [
  {
    id: 'first-movement', unit: 'Statements & method calls',
    title: 'Wake up, little robot.', short: 'First movement', concept: 'Statements · motor power', reward: 'Workshop lights',
    brief: 'Pip is the workshop robot. Give both wheels the same power to roll forward. Travel at least 60 cm, then stop.',
    lesson: 'Motor power is a number from −1.0 to 1.0. Positive means forward. A command stays active until changed. The supplied `if` statement stops Pip after 3 seconds.',
    task: 'Change both `0.0` values to `0.3`. Before running, predict: will Pip move straight or turn?',
    hint: '`setPower(left, right)` controls the two wheels. Equal positive values drive straight. At `0.3`, Pip travels about 30 cm each second.',
    starter: wrap('if (robot.seconds() < 3) {\n    robot.setPower(0.0, 0.0);\n} else {\n    robot.stop();\n}'),
    solution: wrap('if (robot.seconds() < 3) {\n    robot.setPower(0.3, 0.3);\n} else {\n    robot.stop();\n}'),
    explain: 'Why do equal wheel powers make Pip travel straight?',
    target: 'Move ≥ 60 cm · finish stopped',
  },
  {
    id: 'precision-parking', unit: 'Variables & expressions',
    title: 'A place to park.', short: 'Precision parking', concept: 'Variables · arithmetic', reward: 'Charging pad',
    brief: 'The new charging pad is 100 cm ahead. Park Pip inside it, within 8 cm of its center.',
    lesson: 'A `double` stores a decimal number. At full power Pip travels 100 cm/s. At power `0.25`, speed is 25 cm/s. Distance = speed × time.',
    task: 'Keep `power` at `0.25`. Calculate the time needed to travel 100 cm, then change `duration`.',
    hint: '100 cm ÷ 25 cm/s = 4 seconds. This is open-loop control: the time is set without measuring where the robot ended up.',
    starter: wrap('double power = 0.25;\ndouble duration = 1.0;\n\nif (robot.seconds() < duration) {\n    robot.setPower(power, power);\n} else {\n    robot.stop();\n}'),
    solution: wrap('double power = 0.25;\ndouble duration = 4.0;\nif (robot.seconds() < duration) {\n    robot.setPower(power, power);\n} else {\n    robot.stop();\n}'),
    explain: 'Would the same duration work with weaker motors? Why?', target: 'Park on the pad · finish stopped',
  },
  {
    id: 'make-a-turn', unit: 'Comparisons & branching',
    title: 'Think with two wheels.', short: 'Make a turn', concept: 'Comparisons · heading', reward: 'Navigation beacon',
    brief: 'Turn Pip clockwise to face right: a heading of 90°. Stay close to the starting point.',
    lesson: 'Opposite wheel powers turn Pip in place. `heading()` measures the angle in degrees. This `if` is checked again on every update, so the robot can stop when the measurement reaches its target.',
    task: 'Change the right wheel power so Pip rotates instead of driving forward.',
    hint: 'Try `setPower(0.3, -0.3)`. The left wheel goes forward and the right wheel goes backward. Stop once `heading()` reaches `90`.',
    starter: wrap('if (robot.heading() < 90) {\n    robot.setPower(0.3, 0.3);\n} else {\n    robot.stop();\n}'),
    solution: wrap('if (robot.heading() < 90) {\n    robot.setPower(0.3, -0.3);\n} else {\n    robot.stop();\n}'),
    explain: 'What would happen if the two powers were swapped?', target: 'Turn to 90° ± 8° · stay in place',
  },
  {
    id: 'sense-and-stop', unit: 'Sensor feedback',
    title: 'Give Pip a sixth sense.', short: 'Sense & stop', concept: 'Sensors · feedback', reward: 'Parts dispenser',
    brief: 'Approach the far wall and stop 20–40 cm away. The code must work from three starting conditions, including weaker motors.',
    lesson: '`distance()` reports centimeters from Pip’s front to the wall along its heading. Checking this measurement repeatedly is feedback control. The same decision adapts to a different starting distance.',
    task: 'Replace the zero threshold with a stopping distance. The cyan beam shows what the sensor sees.',
    hint: 'Drive while `distance() > 30`; otherwise stop. The runner tests a normal start, a nearer start, and a farther start with weaker motors.',
    starter: wrap('if (robot.distance() > 0) {\n    robot.setPower(0.35, 0.35);\n} else {\n    robot.stop();\n}'),
    solution: wrap('if (robot.distance() > 30) {\n    robot.setPower(0.35, 0.35);\n} else {\n    robot.stop();\n}'),
    explain: 'Why does this work from different starting positions?', target: 'Stop 20–40 cm from wall · pass 3 trials',
  },
  {
    id: 'collect-a-part', unit: 'Boolean logic',
    title: 'A first useful machine.', short: 'Collect a part', concept: 'Booleans · sequencing', reward: 'Assembly bench',
    brief: 'Drive to the dispenser, stop, and pick up a part. Pip can collect only when it is correctly docked.',
    lesson: '`hasPart()` returns a `boolean`: `true` or `false`. The `!` operator means “not.” Once Pip has a part, its first branch keeps it stopped.',
    task: 'Add `robot.collect();` after `robot.stop();` in the final branch. Watch the part appear on Pip.',
    hint: 'The final `else` runs when Pip is close enough and has no part yet. Stop first, then collect. Collection works near the center of the far wall, 15–41 cm away.',
    starter: wrap('if (robot.hasPart()) {\n    robot.stop();\n} else if (robot.distance() > 30) {\n    robot.setPower(0.35, 0.35);\n} else {\n    robot.stop();\n    // Pick up the part here.\n}'),
    solution: wrap('if (robot.hasPart()) {\n    robot.stop();\n} else if (robot.distance() > 30) {\n    robot.setPower(0.35, 0.35);\n} else {\n    robot.stop();\n    robot.collect();\n}'),
    explain: 'Why should collection happen only after the approach?', target: 'Dock + collect + stop · pass 3 trials',
  },
  {
    id: 'autonomous-docking', unit: 'Methods & parameters',
    title: 'Build it independently.', short: 'Autonomous certification', concept: 'Methods · independent transfer', reward: 'Certified robot badge',
    brief: 'Put prior lessons into a reusable `dock` method. The checks call it with target distances of 30, 24, and 36 cm, from different starts.',
    lesson: 'A method packages a behavior. `update` calls `dock` and passes it the `Robot` and a target distance. Use those parameters inside the method instead of hardcoding the target.',
    task: 'Implement `dock` below. The checks call it directly with target distances of 30, 24, and 36 cm. Stop within 4 cm of each requested target, collect a part, and finish stopped.',
    hint: 'Inside `dock`: if the measured distance exceeds `targetDistance`, drive forward. Otherwise stop and collect. Use power `0.35` as a starting point.',
    starter: 'public class Student {\n    public static void update(Robot robot) {\n        dock(robot, 30.0);\n    }\n\n    static void dock(Robot robot, double targetDistance) {\n        // Sense, decide, act.\n    }\n}\n',
    solution: 'public class Student {\n    public static void update(Robot robot) {\n        dock(robot, 30.0);\n    }\n    static void dock(Robot robot, double targetDistance) {\n        if (robot.distance() > targetDistance) {\n            robot.setPower(0.35, 0.35);\n        } else {\n            robot.stop();\n            robot.collect();\n        }\n    }\n}\n',
    explain: 'Compare the 30, 24, and 36 cm trials. Explain how the distance parameter changes the stopping decision.', target: 'Use the distance parameter · pass 3 direct-method trials',
  },
];
